In [13]:
import numpy as np
from PIL import Image
import glob
from numpy import asarray as aa

## Access image directory

In [14]:
def img_array(wd):
    image = Image.open(wd[1])
    array = np.array(image)
    return array

In [15]:
directory = glob.glob("/Users/frederiklindvig/Desktop/Python_pathology/PathologyInput/*.jpeg")
array = img_array(directory)

In [16]:
print(array.shape)

(1529, 1256, 3)


In [17]:
numpydata = aa(array)
print(numpydata)

[[[213 212 220]
  [218 215 224]
  [214 211 220]
  ...
  [233 233 243]
  [233 233 243]
  [233 233 243]]

 [[196 193 200]
  [204 201 210]
  [205 202 213]
  ...
  [233 233 243]
  [233 233 243]
  [233 233 243]]

 [[199 196 203]
  [201 198 209]
  [197 193 208]
  ...
  [233 233 243]
  [233 233 243]
  [233 233 243]]

 ...

 [[236 236 246]
  [235 235 245]
  [235 235 245]
  ...
  [235 235 245]
  [235 235 245]
  [235 235 245]]

 [[236 236 246]
  [235 235 245]
  [235 235 245]
  ...
  [235 235 245]
  [235 235 245]
  [235 235 245]]

 [[235 235 245]
  [235 235 245]
  [235 235 245]
  ...
  [235 235 245]
  [235 235 245]
  [235 235 245]]]
